= Advanced Deployment of AAP 2.5
:navtitle: Home

== Introduction

Ansible Automation Platform (AAP) enables scalable IT automation across complex environments. One of its features is an Automation Mesh which helps with efficient task distribution and coordination. Proper AAP sizing based on workload and infrastructure is crucial for optimal deployment. In this training we will look at what needs to be considered during AAP deployment to ensure performance, and learn some tips for effective troubleshooting of installation issues.

Duration: 60 minutes

== Objectives

On completing this course, you will:

- Understand the Automation Mesh;
- Learn how to calculate the sizing requirements for AAP;
- Know how to troubleshoot AAP installation issues;
- Performance consideration while doing the deployment. 

== Prerequisites

This course assumes that you have the following prior experience:

- Foundational knowledge of Linux, Containers, and Ansible. 
- https://training-lms.redhat.com/sso/saml/auth/rhlpint?RelayState=deeplinkoffering%3D73946012[Basic Deployment of Ansible Automation Platform 2.5,windows=_blank].


== Contributors

The PTL team acknowledges the valuable contributions of the following Red Hat associates:

- Konstantin Kuminsky (Contributor)
- Amrinder Singh (Content Architect)
- Rutuja Deshmukh (Editor)
- Anna Swicegood (Learning Product Manager)
