= Automation Mesh Hands-on Lab

Once the lab is deployed, access the system via *ssh* terminal and make sure to run all commands as a regular user and use the sudo command to perform any root-level operations. Watch the video or simply follow the steps below.

video::advanced-aap-2.5.mp4[align="left",width=800,height=500]

. Install required tools:
+
[source,bash,role=execute]
----
 $ sudo dnf install -y wget git-core rsync vim ansible-core
----

. Copy the content of the `/home/devops/inventory` file into a notepad for further use. 
+
[source,bash,role=execute]
----
$ cat /home/devops/inventory
----

. Extract *installer file* contents:
+
[source,bash,role=execute]
----
$ tar -xvf ansible-automation-platform-containerized-setup-bundle-2.5-3-x86_64.tar.gz
$ cd ansible-automation-platform-containerized-setup-bundle-2.5-3-x86_64.
----

. Ensure the `inventory-growth` file has the following: 

+
[source,bash,role=execute]
----
[automationgateway]
aap2.g8hpb.internal

[automationcontroller]
aap-controller.g8hpb.internal

[automationhub]

[automationeda]

[database]
aap-database.g8hpb.internal

[execution_nodes]
aap-execution.g8hpb.internal

[all:vars]

postgresql_admin_username=postgres
postgresql_admin_password=redhat

bundle_install=true
bundle_dir='{{ lookup("ansible.builtin.env", "PWD") }}/bundle'

redis_mode=standalone

gateway_admin_password=redhat
gateway_pg_host=aap-database.g8hpb.internal
gateway_pg_password=redhat

controller_admin_password=redhat
controller_pg_host=aap-database.g8hpb.internal
controller_pg_password=redhat
----


. Perform AAP installation:
+
[source,bash,role=execute]
----
$ ansible-playbook -i inventory-growth ansible.containerized_installer.install
----

. Access AAP using the `aap2` hostname by removing the `internal` at the end and adding the `sandboxid` to the hostname from the `RHDP` lab login details section. 
+
[source,bash,role=execute]
----
aap2.g8hpb.sandbox3274.opentlc.com
----
 Note: `aap2.<random-ID-according-to-your-deplyoment>.<sandboxid>.opentlc.com` will be your main URL to access it via web.  

. Use the user *admin* and the *password* set in the inventory-growth file. In the video it was set to *redhat*. 

 Note: Use a stronger password while doing the real-life deployment.

. Provide the *Red Hat login ID* to get the available subscriptions and choose *60-day subscription to Red Hat Ansible® Automation Platform* or *Red Hat Developer Subscription for Individuals* for this lab.

. After *Login* run the *Project sync* for the *Demo project* to confirm the job is getting executed.

. In *Automation Execution* click on *Templates* and edit the *Demo Job Template*. 

. Click on *Instance groups* and select *executionplane* and save the job template. 

. Run the job for *Demo Job Template*. 

. Go to jobs *select Demo Job Template* and check the *Details* section in the job and verify it's getting executed on the Execution Plane node.

. Go to *Automation Execution* then *Infrastructure* and check the *Topology View* for the current architecture of Ansible Automation Platform.
