= Example on Calculating the Size

At this point we should have a good idea how to calculate capacity and what factors to consider. Let's go through a planning exercise.

For this example, the cluster must support the following capacity: 	

- 500 managed hosts 					
- 1,000 tasks per hour per host or 16 tasks per minute per host 				
- 10 concurrent jobs 					
- Forks set to 5 on playbooks. This is the default. 					
- The average event size is 1 Mb 					

The virtual machines have 4 CPUs and 16 GB RAM, and disks have 3000 IOPs. 	

*Execution Capacity calculation*

Execution Capacity = (Number of jobs * forks value) + (number of jobs * 1 base task impact of a job)

Calculate this using the equation: (10 jobs * 5 forks) + (10 jobs * 1 base task impact of a job) = 60 execution capacity.			

*Control Capacity*

Total tasks/min = 500 Managed hosts * 16 tasks per minute
                         = 8000 tasks/minute = 133 tasks/second

In other words 133 events will be generated every second. 

Note: Usually it's a good idea to run the job to see exactly how many events it produces, as this depends on the specific task and verbosity level. For example, a debug task printing “Hello World” produces 6 job events per host with the verbosity of 1. Verbosity of 3 creates 34 job events per host. Therefore, a task produces at least 6 events.

Assuming 6 events per task, 133 tasks/second will generate 133 * 6 = 798 events/second consuming 798 MB per second for logs/event data. In other words, our Control node must be able to process around 789 events of data per second and it should have an execution capacity of 60 forks.

Considering the reservation and virtual machine we have deployed we get around 140 forks which is more than the required 60. Therefore a minimum of one node is needed. However two nodes are recommended for redundancy.

To summarise, we will need to deploy 1 execution node, 1 control node, 1 database node, and 1 Unified UI node (mandatory for AAP 2.5) of 4 CPUs at 2.5Ghz, 16 GB RAM, and disks that have about 3000 IOPs to handle the infrastructure for the requirements we were given.

Note: The above is true for RPM and Containerized environments. Openshift related content will be added later.
