= Performance Consideration 

In the previous chapter we discussed how to calculate node size. The following will also help with planning the deployment for the Control and Execution plane.

The Default Parameters that likely do not need to be changed unless we know a specific value and the reason why it's needed:

. Facts size per host - 50 KB
. Size per event - 2 KB
. Events per tasks - 10
. Memory per fork - 100 MB
. Forks per CPU - 4
. Capacity Adjustment - 1.0 (i.e. select highest value)
. Execution Environment average size - 450 MB
. Automation Controller capacity - 400 events/s
. Automation Controller RAM per event fork - 10 KB
. Automation Controller CPU per event fork - 0.0001 
. Concurrent API calls per controller - 100 (up to 300 calls is allowed)
. Controller/execution base job capacity for every job run - 1


The factors that vary across different environments: 

- Number of Ansible Managed hosts/nodes.
- Number of jobs per host per day.
- Tasks run per playbook or job including the imported roles/tasks/playbooks. 
- Jobs are running for a specific time-period or 24X7. 

Few helpful formulas:

[source]
----
Total Jobs = (Number of Hosts × Jobs per Host per Day) ÷ Hosts Required per Job

Job Duration = Job Duration per Host × CEILING(Hosts per Job ÷ Parallel Forks)

Workload Utilization = (Jobs per Day × Job Duration) ÷  Automation Hours per Day

Polling Load = (Jobs per Day × Job Duration) ÷ Polling Interval

API Utilization = (API Calls per Day × API Call Duration) ÷ Automation Hours per Day

Database size for facts  = Facts size of hosts * number of hosts / 1024

Database size for Inventory will be similar to size of database facts. 

Database size for jobs = number of hosts * jobs per host per data * Number of days to keep the data * Number of events * event  size / 1024 
----

Database RAM and CPU should be something similar to the RAM and CPU or control plane or execution plane, whichever is higher. 
