= Troubleshooting Ansible Automation Platform Installation Issue

In case of RPM/Containerized installation the scripts are only automating the tasks that can be performed manually. So the basic rule of thumb for resolving AAP installation issues is to troubleshoot by running tasks manually. This helps isolate the issue and also ensures that the steps are executed under the same user.

Troubleshooting suggestions:

. Increase the verbosity while running the script by just adding -vvv in the last and it will provide more verbose output while running the automation script tasks for setting up for the ansible automation platform. 

.. Level 1 (-v)  describes the below: 
- Task results including any changed/failed details.
- Module output (stdout/stderr of commands).
- Useful for seeing why something failed.
+
For example:
+
[source]
----
TASK [ansible.containerized_installer.common : Set ostree-based OS fact] ********************************
ok: [localhost] => {"ansible_facts": {"ostree": false}, "changed": false}
----

- This level is helpful for simple debugging, checking why something changed or failed, and identifying which file and which task was where it failed.

.. Level 2 (-vv) describes the below: 
- More info on variables and task parameters
- SSH arguments and remote command details
- What Ansible is sending to the remote host and the location of the file which is getting executed. 
+
Example: 
+
[source]
----
TASK [ansible.containerized_installer.preflight : Ensure postgresql admin password is provided] *********
task path: /home/lab-user/ansible-automation-platform-containerized-setup-bundle-2.5-12-x86_64/collections/ansible_collections/ansible/containerized_installer/roles/preflight/tasks/database.yml:30
ok: [localhost] => {
	"changed": false,
	"msg": "All assertions passed"
}
----

- This level can be used to see variables or arguments.

.. Level 3 (-vvv) describes the below: 
- Connection details, SSH-level debug
- Exact shell commands being executed on the remote machine
- Fact gathering (detailed facts about hosts)
- Module file paths
+
Example : 
+
[source]
----
TASK [Gather facts] *************************************************************************************
task path: /home/lab-user/ansible-automation-platform-containerized-setup-bundle-2.5-12-x86_64/collections/ansible_collections/ansible/containerized_installer/playbooks/install.yml:8
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: lab-user
<127.0.0.1> EXEC /bin/sh -c 'echo ~lab-user && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/lab-user/.ansible/tmp `"&& mkdir "` echo /home/lab-user/.ansible/tmp/ansible-tmp-1745343613.5557938-21925-131051723522629 `" && echo ansible-tmp-1745343613.5557938-21925-131051723522629="` echo /home/lab-user/.ansible/tmp/ansible-tmp-1745343613.5557938-21925-131051723522629 `" ) && sleep 0'
Using module file /usr/lib/python3.9/site-packages/ansible/modules/setup.py
<127.0.0.1> PUT /home/lab-user/.ansible/tmp/ansible-local-21921anxpgqif/tmpqek1dip5 TO /home/lab-user/.ansible/tmp/ansible-tmp-1745343613.5557938-21925-131051723522629/AnsiballZ_setup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/lab-user/.ansible/tmp/ansible-tmp-1745343613.5557938-21925-131051723522629/ /home/lab-user/.ansible/tmp/ansible-tmp-1745343613.5557938-21925-131051723522629/AnsiballZ_setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 /home/lab-user/.ansible/tmp/ansible-tmp-1745343613.5557938-21925-131051723522629/AnsiballZ_setup.py && sleep 0'
----
+
- This level helps with Debugging SSH issues or checking the exact remote commands. 

. If you are facing any issue with the script you will be facing an issue with the manual tasks as well. Thus, identify the task and fix the issue manually with the help of your RHEL administrator if needed.

. Using the Red Hat suggested rpm repositories and reading the error properly will help you resolve 90% of the issues: 
+
For example: 
+
[source]
----
TASK [ansible.automation_platform_installer.preflight : Preflight check - Fail if this machine lacks sufficient RAM.] ***
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "This machine does not have sufficient RAM to run Ansible Automation Platform."}
----
+
- The error suggests an issue with the RAM, so increasing memory should resolve the problem. Similarly, the other errors also point to common issues of the system that result in the installation issues. 

. In addition consider searching through KB articles https://access.redhat.com/search/[Red Hat Knowledge Base] for known issues/solutions and Jira tickets for reported bugs https://issues.redhat.com/projects/AAP/issues[Jira]

The above should be enough to resolve the installation issues. Further, here are a few commonly faced installation issues: 

- https://access.redhat.com/solutions/7096052[Ansible Automation Platform 2.5 Installer fails with Bad API request: 502 Server Error: Bad Gateway for url, windows=_blank]
- https://access.redhat.com/solutions/7105447[Ansible Automation Platform 2.5 Installer fails at TASK "ansible.automation_platform_installer.automationgateway : Migrate data" ,windows=_blank]
- https://access.redhat.com/solutions/7099900[RPM Installation of AAP 2.5 throws (HTTP Error 502: Bad Gateway): api/gateway/v1/, windows=_blank]
