= Troubleshooting Ansible Automation Platform Installation issue.

For the RPM/Containerized Installation: 

As the script are only automating the tasks that can be performed manually so the basic thumb rule for resolving Installation issue for the ansible automation platform on the RPM and containerized installer is to implement the steps manually what is being performed by the script to isolate the issue and also to make sure to run that with normal user with which script is running and use sudo command while running it to depict the same behaviour as of ansible: 

. Increase the verbosity  while running the script but just adding -vvv in the last and it will provide more verbose output while running the automation script tasks for setting up for the ansible automation platform. 

.. Level 1 (-v)  describes the below: 
- Task results including any changed/failed details
- Module output (stdout/stderr of commands)
- Useful for seeing why something failed.
+
For eg: 
+
[source]
----
TASK [ansible.containerized_installer.common : Set ostree-based OS fact] ********************************
ok: [localhost] => {"ansible_facts": {"ostree": false}, "changed": false}
----

- The above is useful for simple debugging, checking why something changed or failed and which file and which tasks was where it failed. 

.. Level 2 (-vv) describes the below: 
- More info on variables and task parameters
- SSH arguments and remote command details
- What Ansible is sending to the remote host and the location of the file which is getting executed. 
+
Example: 
+
[source]
----
TASK [ansible.containerized_installer.preflight : Ensure postgresql admin password is provided] *********
task path: /home/lab-user/ansible-automation-platform-containerized-setup-bundle-2.5-12-x86_64/collections/ansible_collections/ansible/containerized_installer/roles/preflight/tasks/database.yml:30
ok: [localhost] => {
	"changed": false,
	"msg": "All assertions passed"
}
----

- This will be helpful to see what variables or args are being used.

.. Level 3 (-vvv) describes the below: 
- Connection details, SSH-level debug
- Exact shell commands being executed on the remote machine
- Fact gathering (detailed facts about hosts)
- Module file paths
+
Example : 
+
[source]
----
TASK [Gather facts] *************************************************************************************
task path: /home/lab-user/ansible-automation-platform-containerized-setup-bundle-2.5-12-x86_64/collections/ansible_collections/ansible/containerized_installer/playbooks/install.yml:8
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: lab-user
<127.0.0.1> EXEC /bin/sh -c 'echo ~lab-user && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/lab-user/.ansible/tmp `"&& mkdir "` echo /home/lab-user/.ansible/tmp/ansible-tmp-1745343613.5557938-21925-131051723522629 `" && echo ansible-tmp-1745343613.5557938-21925-131051723522629="` echo /home/lab-user/.ansible/tmp/ansible-tmp-1745343613.5557938-21925-131051723522629 `" ) && sleep 0'
Using module file /usr/lib/python3.9/site-packages/ansible/modules/setup.py
<127.0.0.1> PUT /home/lab-user/.ansible/tmp/ansible-local-21921anxpgqif/tmpqek1dip5 TO /home/lab-user/.ansible/tmp/ansible-tmp-1745343613.5557938-21925-131051723522629/AnsiballZ_setup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/lab-user/.ansible/tmp/ansible-tmp-1745343613.5557938-21925-131051723522629/ /home/lab-user/.ansible/tmp/ansible-tmp-1745343613.5557938-21925-131051723522629/AnsiballZ_setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 /home/lab-user/.ansible/tmp/ansible-tmp-1745343613.5557938-21925-131051723522629/AnsiballZ_setup.py && sleep 0'
----
+
- This will help in Debugging SSH issues or checking the exact remote commands. 

. If you are facing the issue with the script you will be facing the issue with the manual tasks as well identify the task and fix the issue manually with the help of System 
administrator if needed.

. Using the Red Hat suggested rpm repositures and Reading the error properly will help you resolve the 90% of the issues: 
+
For example: 
+
[source]
----
TASK [ansible.automation_platform_installer.preflight : Preflight check - Fail if this machine lacks sufficient RAM.] ***
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "This machine does not have sufficient RAM to run Ansible Automation Platform."}
----
+
- From the abve error if we read it points to the issue with the RAM so increasing it will resolve the issue. Similarly the other errors also point to common issues of the system that results in the installation issues. 

The above should be enough to resolve the Installation issues further here are few commonly faced Installation issues: 

- https://access.redhat.com/solutions/7096052[Ansible Automation Platform 2.5 Installer fails with Bad API request: 502 Server Error: Bad Gateway for url, windows=_blank]
- https://access.redhat.com/solutions/7105447[Ansible Automation Platform 2.5 Installer fails at TASK "ansible.automation_platform_installer.automationgateway : Migrate data" ,windows=_blank]
- https://access.redhat.com/solutions/7099900[RPM Installation of AAP 2.5 throws (HTTP Error 502: Bad Gateway): api/gateway/v1/, windows=_blank]
