= Example on calculating the size

From the previous section you must have figured out the workload capacity that you want to support, you must plan your deployment based on the requirements of the workload. To help you with your deployment, review the following planning exercise. 			

For this example, the cluster must support the following capacity: 	

- 500 managed hosts 					
- 1,000 tasks per hour per host or 16 tasks per minute per host 				
- 10 concurrent jobs 					
- Forks set to 5 on playbooks. This is the default. 					
- Average event size is 1 Mb 					

The virtual machines have 4 CPU and 16 GB RAM, and disks that have 3000 IOPs. 	

*Execution Capacity calculation*

Execution Capacity = (Number of jobs * forks value) + (number of jobs * 1 base task impact of a job)

You calculate this by using the following equation: (10 jobs * 5 forks) + (10 jobs * 1 base task impact of a job) = 60 execution capacity 				

*Control Capacity*

Total tasks/min = 500 Managed hosts * 16 tasks per minute
                         = 8000 tasks/ minute 

The above also means that 8000 events will be generated every minute. 

 Note: You must run the job to see exactly how many events it produces, because this is dependent on the specific task and verbosity. For example, a debug task printing “Hello World” produces 6 job events with the verbosity of 1 on one host. With a verbosity of 3, it produces 34 job events on one host. Therefore, you must estimate that the task produces at least 6 events and rest depends on the number of jobs and verbosity on which you are running it which varies from organization to organization.

Lets assume that there are 6 events generated per task and there are `8000/60 tasks/second = 133 tasks per second`

Now from the above example each event is of 1 mb in size. 

Lets estimate the event: 

Number of tasks/sec * Events per tasks = events per second. 
133 * 6 = 798 events per second and each event is of 1 mb so 798 mb per second for logs / event data. 

Your control node must be able to process around 789 events of data per second and it should have Execution capacity of 60. 

Now considering the reservation and virtual machine we have deployed we get around 140 forks. 

Number of Execution Nodes = Required Forks / Forks per Node

[source]
----
 60 / 140  which is less than 1. So minimum 1 node will be needed and 2 nodes to implement a fail-safe mechanism. 
----

So for the above: 

You need to deploy 1 execution node, 1 control node, 1 database node and 1 Unified UI node (mandatory for AAP 2.5) of 4 CPU at 2.5Ghz, 16 GB RAM, and disks that have about 3000 IOPs to handle the Infrastructure for the below requirement: 

 - 500 managed hosts 					
- 1,000 tasks per hour per host or 16 tasks per minute per host 				
- 10 concurrent jobs 					
- Forks set to 5 on playbooks. This is the default. 					
- Average event size is 1 Mb 		

 Note: 
 The above is true for RPM and Containerized environment.
